"""esquema inicial etapa 1

Las 9 tablas del panel. Ajuste a mano sobre el autogenerate: FechaUTC
(TypeDecorator de app.models) se emite como su tipo real,
sa.DateTime(timezone=True), para no depender del código de la app.

Revision ID: 866ed55c8961
Revises: 
Create Date: 2026-09-04 23:42:28.018650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '866ed55c8961'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consorcio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('cuit', sa.String(length=13), nullable=False),
    sa.Column('admin_nombre', sa.String(length=200), nullable=False),
    sa.Column('admin_cuit', sa.String(length=13), nullable=False),
    sa.Column('marca', sa.String(length=120), nullable=False),
    sa.Column('umbrales', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liquidaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('sistema', sa.String(length=40), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('archivo_key', sa.String(length=500), nullable=False),
    sa.Column('datos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('cuadra', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo')
    )
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uf', sa.Integer(), nullable=False),
    sa.Column('piso_depto', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('propietario', sa.String(length=200), nullable=False),
    sa.Column('porcentuales', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('codigo_hash', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uf')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('clave_hash', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liquidacion_id', sa.Integer(), nullable=False),
    sa.Column('gasto_n', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('archivo_key', sa.String(length=500), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('metadatos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liquidacion_id', sa.Integer(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=False),
    sa.Column('proveedor', sa.String(length=200), nullable=False),
    sa.Column('concepto', sa.Text(), nullable=False),
    sa.Column('columna', sa.String(length=10), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('factura_fecha', sa.Date(), nullable=True),
    sa.Column('factura_nro', sa.String(length=40), nullable=True),
    sa.Column('factura_importe', sa.Float(), nullable=True),
    sa.Column('pagos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liquidacion_id', 'n')
    )
    op.create_table('hallazgos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liquidacion_id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=500), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('regla', sa.String(length=40), nullable=False),
    sa.Column('severidad', sa.String(length=10), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('evidencia', sa.Text(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('recomendacion', sa.Text(), nullable=False),
    sa.Column('refs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('publicado', sa.Boolean(), nullable=False),
    sa.Column('respuesta_admin', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liquidacion_id', 'origen', 'clave')
    )
    op.create_table('informes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liquidacion_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('archivo_key', sa.String(length=500), nullable=False),
    sa.Column('marca', sa.String(length=120), nullable=False),
    sa.Column('publicado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liquidacion_id', 'tipo')
    )
    op.create_table('hallazgo_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hallazgo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('de', sa.String(length=20), nullable=False),
    sa.Column('a', sa.String(length=20), nullable=False),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hallazgo_id'], ['hallazgos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hallazgo_eventos')
    op.drop_table('informes')
    op.drop_table('hallazgos')
    op.drop_table('gastos')
    op.drop_table('documentos')
    op.drop_table('usuarios')
    op.drop_table('unidades')
    op.drop_table('liquidaciones')
    op.drop_table('consorcio')
    # ### end Alembic commands ###
